### ISSUE TITLE
Feature idea: Get Telegram message

### ISSUE THREAD

**Issue by fez6** [alvaroBegnini/bot-manager-telegram#2]
I think it would be pretty cool if you could implement a function for getting the messages that are being send to the bot.

**Comment by alvaroBegnini** [comment]
Hello and thanks for your comment.
You mean a function for get the messages sent through the application or a function for get the responses in the chat?

**Comment by fez6** [comment]
> Hello and thanks for your comment. You mean a function for get the messages sent through the application or a function for get the responses in the chat?

A function to get the responses in the chat would be great! :)

**Comment by alvaroBegnini** [comment]
A new release with a function to get the responses in the chat is now available in the last version

**Comment by fez6** [comment]
> A new release with a function to get the responses in the chat is now available in the last version

Thank you soooo much @alvaroBegnini <3

**Comment by alvaroBegnini** [comment]
A new release with callbacks is coming this week
