### ISSUE TITLE
TelegramBot is not a constructor

### ISSUE THREAD

**Issue by fez6** [alvaroBegnini/bot-manager-telegram#3]
When running my bot I get the following error:
```js
const tbot = new TelegramBot(ttoken, chatid);
             ^

TypeError: TelegramBot is not a constructor
```
Of course `token` & `chatid` are declared right, I know this because before updating to version 1.2.5 that code still worked.
Apparently this is a reoccurring error.

**Comment by alvaroBegnini** [comment]
I think this is because the import
If you're using require it should be like this

```js
const TelegramBot = require("telegram-bot-nodejs").default; 
```

If you're using import

```typescript
Import TelegramBot from "telegram-bot-nodejs"
```

**Comment by fez6** [comment]
I think you misunderstood me, that was the error I am getting when I am trying to construct a bot my first three lines of code look like this:
```js
const TelegramBot = require("telegram-bot-nodejs");

const tbot = new TelegramBot(ttoken, chatid);
```
I already required `telegram-bot-nodejs` and I am now trying to construct the bot to for example send a message. 
But for some reason I get a `TypeError` saying that `new TelegramBot(ttoken, chatid);` is not working because:
 `TelegramBot is not a constructor` everytime I try to run this code.
There is nothing wrong with the token or the chat-ID since it worked in the previous version.
I think something got messed up in the module, but since my TypeScript knowledge is very limited I can not really help you in finding or fixing the error.

**Comment by alvaroBegnini** [comment]
You're missing the .default at the import

change 
```js
const TelegramBot = require("telegram-bot-nodejs")
```
To
```js
const TelegramBot = require("telegram-bot-nodejs").default; 
```

I'll change the syntax import back to normal in the release of next week but for now you have to import this way

**Comment by fez6** [comment]
Man I didn't even see the `.default` 😅
Thanks for the help and sorry for the inconvenience! <3

**Comment by alvaroBegnini** [comment]
No problem
If you have any questions please post it in a new issue
It's the way that I can improve the project's quality
Thank you
